import './globals.css'
import type { Metadata } from 'next'

import { CssBaseline } from '@mui/material';

export const metadata: Metadata = {
  title: 'Minsta',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <CssBaseline />
      <body>{children}</body>
    </html>
  )
}